config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  #root to: "home#index"
  root "projects#index"
  resources :projects
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
    validates_presence_of :title, :description
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!, except: [:index, :show]

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  #before_action :authenticate_user!

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CS 3300</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <!--<p class="notice"><%= notice %></p>-->
    <!--<p class="alert"><%= alert %></p>-->
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <div class="container-fluid mt-3">
    <p class="text-white bg-dark text-center">
      <%= project.title %>
    </p>
  </div>

  <div class="container-fluid mt-3">
    <p>
      <%= project.description %>
    </p>
  </div>

</div>

app/views/projects/edit.html.erb
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp</p>

<div class="row">
  <div class="col-md-3 mx-auto rounded text-white bg-dark" style="border: 2px solid black;">
    <h1>Editing project</h1>

    <%= render "form", project: @project %>

    <br>

    <div>
      <div class="btn btn-primary btn-sm my-2"><%= link_to "Show this project", @project, :class => "btn" %></div>
      <div class="btn btn-primary btn-sm my-2"><%= link_to "Back to projects", projects_path, :class => "btn" %></div>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp</p>

<p style="color: green"><%= notice %></p>

<% if user_signed_in?%> 
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
  <div class="container-fluid justify-content-end">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link active" href="/users/sign_out">
          Sign Out
        </a>
      </li>
    </ul>
  </div>  
  </nav>
<% else %>
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
    <div class="container-fluid justify-content-end">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" href="/users/sign_in">
            Sign In
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="/users/sign_up">
            Sign Up
          </a>
        </li>
      </ul>
    </div>  
  </nav>
<% end %>

<h1 class="display-5 text-center">Projects</h1>

<div id="projects" class="row gx-5 gy-2">
  <% @projects.each do |project| %>
    <div class="col-md-4" style="border: 2px solid black;">
      <header>
        <%= render project %>
        <p>
          <div class="btn btn-secondary btn-sm my-1"><%= link_to "Show this project", project, :class => "btn" %></div>
        </p>
      <header>
    </div>
  <% end %>
</div>

<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp</p>
  
<div class="d-grid gap-5">
  <a class="btn btn-primary " href="/projects/new" role="button">New Project</a>
</div>

app/views/projects/new.html.erb
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp</p>

<div class="row">
  <div class="col-md-3 mx-auto rounded text-white bg-dark" style="border: 2px solid black;">
    <h1>New project</h1>

    <%= render "form", project: @project %>

    <br>

    <div>
      <div class="btn btn-primary btn-sm my-2"><%= link_to "Back to projects", projects_path , :class => "btn" %></div>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project %>

<div class="display-8 text-center">
  <div class="btn btn-secondary btn-sm my-1"><%= link_to "Edit this project", edit_project_path(@project), :class => "btn" %></div>
  <div class="btn btn-secondary btn-sm my-1"><%= link_to "Back to projects", projects_path, :class => "btn" %></div>

  <%= button_to "Destroy this project", @project, method: :delete %>
</div>